---
- name: Personal OS Setup
  hosts: localhost
  become: yes

  tasks:
    # 1️⃣ System Update & Upgrade
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: dist

    # 2️⃣ Install Essential System Tools
    - name: Install essential system tools
      apt:
        name:
          - git
          - curl
          - wget
          - net-tools
          - libssl-dev
          - build-essential
        state: present

    # Install Snap
    - name: Install Snap package manager
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Ensure Snap service is started and enabled
      systemd:
        name: snapd
        enabled: yes
        state: started

    # 3️⃣ Configure Git
    - name: Configure Git username and email
      shell: |
        git config --global user.name "naseriboroujeni"
        git config --global user.email "naseriboroujeni@gmail.com"

    # 4️⃣ Install Programming Languages & Runtimes
    - name: Install OpenJDK 21
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Install Rust using rustup
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: /home/{{ ansible_user_id }}/.cargo/bin/rustc

    - name: Install WasmEdge
      shell: curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash
      args:
        creates: /usr/local/bin/wasmedge

    # 5️⃣ Install Development Tools
    - name: Install VS Code
      snap:
        name: code
        classic: yes

    - name: Install IntelliJ IDEA Community Edition
      snap:
        name: intellij-idea-community
        classic: yes

    - name: Install RustRover
      snap:
        name: rustrover
        classic: yes

    - name: Install DBeaver Community Edition
      snap:
        name: dbeaver-ce

    - name: Install Postman
      snap:
        name: postman

    - name: Install Microsoft Teams (Linux)
      snap:
        name: teams-for-linux
        classic: yes

    # 6️⃣ Install Multimedia Apps
    - name: Install Google Chrome
      shell: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
        apt update
        apt install -y google-chrome-stable
      args:
        creates: /usr/bin/google-chrome

    - name: Install VLC
      apt:
        name: vlc
        state: present

    - name: Install Cheese (Camera App)
      apt:
        name: cheese
        state: present

    # 7️⃣ Install Docker & PostgreSQL Container
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Create a PostgreSQL Docker container
      shell: |
        docker run --name postgres -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin -p 5432:5432 -d postgres
      args:
        creates: /var/lib/docker/containers

    # 8️⃣ Install GNOME Extensions
    - name: Install GNOME Shell Extensions and Dependencies
      apt:
        name:
          - gnome-shell-extensions
          - chrome-gnome-shell
        state: present

    - name: Install gnome-extensions-cli
      shell: |
        wget -O gnome-extensions-cli \
        https://github.com/essembeh/gnome-extensions-cli/releases/latest/download/gnome-extensions-cli
        chmod +x gnome-extensions-cli
        mv gnome-extensions-cli /usr/local/bin/
      args:
        creates: /usr/local/bin/gnome-extensions-cli

    - name: Install Dash to Panel
      shell: "gnome-extensions-cli install dash-to-panel@jderose9.github.com"

    - name: Install Clipboard Indicator
      shell: "gnome-extensions-cli install clipboard-indicator@tudmotu.com"

    - name: Enable Dash to Panel
      shell: "gnome-extensions enable dash-to-panel@jderose9.github.com"

    - name: Enable Clipboard Indicator
      shell: "gnome-extensions enable clipboard-indicator@tudmotu.com"

    - name: Restart GNOME Shell (needed for changes to take effect)
      shell: "killall -SIGQUIT gnome-shell"
      ignore_errors: yes
